auth:
  region: us-phoenix-1
  tenancy: ocid1.tenancy.oc1..aaaaaaaatyn7scrtwtqedvgrxgr2xunzeo6uanvyhzxqblctwkrpisvke4kq
  user: ocid1.user.oc1..aaaaaaaai77mql2xerv7cn6wu3nhxang3y4jk56vo5bn5l5lysl34avnui3q
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    <snip>
    -----END RSA PRIVATE KEY-----
  # Omit if there is not a password for the key
  key_passphrase: supersecretpassword
  fingerprint: 8c:bf:17:7b:5f:e0:7d:13:75:11:d6:39:0d:e2:84:74

# compartment configures Compartment within which the cluster resides.
compartment: ocid1.compartment.oc1..aaaaaaaa3um2atybwhder4qttfhgon4j3hcxgmsvnyvx4flfjyewkkwfzwnq

# vcn configures the Virtual Cloud Network (VCN) within which the cluster resides.
vcn: ocid1.vcn.oc1..aaaaaaaask7mpk4mij3pnm6yvnntte25ffadxiivpokxevfxgtsu6ftkqhrq

loadBalancer:
  # disableSecurityListManagement disables the automatic creation of ingress
  # rules for the node subnets and egress rules for the load balancers to the
  # node subnets.
  #
  # If security list management is disabled, then it requires that the user
  # has setup a rule that allows inbound traffic to the appropriate ports
  # for kube proxy health port, node port ranges, and health check port ranges.
  # E.g. 10.82.0.0/16 30000-32000
  disableSecurityListManagement: false

  # subnet1 configures one of two subnets to which load balancers will be added.
  # OCI load balancers require two subnets to ensure high availability.
  subnet1: ocid1.subnet.oc1.phx.aaaaaaaasa53hlkzk6nzksqfccegk2qnkxmphkblst3riclzs4rhwg7rg57q

  # subnet2 configures the second of two subnets to which load balancers will
  # be added.  OCI load balancers require two subnets to ensure high
  # availability.
  subnet2: ocid1.subnet.oc1.phx.aaaaaaaahuxrgvs65iwdz7ekwgg3l5gyah7ww5klkwjcso74u3e4i64hvtvq
