apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  generation: 1
  name: csi-oci-{{ if .Values.customHandle }}{{ .Values.customHandle }}-{{ end }}controller
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: csi-oci-{{ if .Values.customHandle }}{{ .Values.customHandle }}-{{ end }}controller
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csi-oci-{{ if .Values.customHandle }}{{ .Values.customHandle }}-{{ end }}controller
        role: csi-oci{{ if .Values.customHandle }}-{{ .Values.customHandle }}{{ end }}
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      containers:
        - name: csi-volume-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.0.1
          args:
            - --csi-address=/var/run/shared-tmpfs/csi.sock
            - --volume-name-prefix=csi
            - --feature-gates=Topology=true
            - --timeout=120s
            - --leader-election
            - --leader-election-namespace=kube-system
          volumeMounts:
            - name: config
              mountPath: /etc/oci/
              readOnly: true
            - mountPath: /var/run/shared-tmpfs
              name: shared-tmpfs
        - name: csi-fss-volume-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.0.1
          args:
            - --csi-address=/var/run/shared-tmpfs/csi-fss.sock
            - --volume-name-prefix=csi-fss
            - --feature-gates=Topology=true
            - --timeout=120s
            - --leader-election
            - --leader-election-namespace=kube-system
          volumeMounts:
            - name: config
              mountPath: /etc/oci/
              readOnly: true
            - mountPath: /var/run/shared-tmpfs
              name: shared-tmpfs
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.6.1
          args:
            - --csi-address=/var/run/shared-tmpfs/csi.sock
            - --timeout=120s
            - --leader-election=true
            - --leader-election-namespace=kube-system
          volumeMounts:
            - name: config
              mountPath: /etc/oci/
              readOnly: true
            - mountPath: /var/run/shared-tmpfs
              name: shared-tmpfs
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.11.1
          args:
            - --csi-address=/var/run/shared-tmpfs/csi.sock
            - --leader-election
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /var/run/shared-tmpfs
              name: shared-tmpfs
        - name: snapshot-controller
          image: registry.k8s.io/sig-storage/snapshot-controller:v6.3.0
          args:
            - --leader-election
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /var/run/shared-tmpfs
              name: shared-tmpfs
        - name: csi-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.0
          args:
            - --csi-address=/var/run/shared-tmpfs/csi.sock
            - --leader-election
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /var/run/shared-tmpfs
              name: shared-tmpfs
        - name: oci-csi-{{ if .Values.customHandle }}{{ .Values.customHandle }}-{{ end }}controller-driver
          args:
            - --endpoint=unix://var/run/shared-tmpfs/csi.sock
            - --fss-csi-endpoint=unix://var/run/shared-tmpfs/csi-fss.sock
          command:
            - /usr/local/bin/oci-csi-controller-driver
          image: iad.ocir.io/oracle/cloud-provider-oci:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BLOCK_VOLUME_DRIVER_NAME
              value: "{{ if .Values.customHandle }}{{ .Values.customHandle }}.{{ end }}blockvolume.csi.oraclecloud.com"
            - name: FSS_VOLUME_DRIVER_NAME
              value: "{{ if .Values.customHandle }}{{ .Values.customHandle }}.{{ end }}fss.csi.oraclecloud.com"
          volumeMounts:
            - name: config
              mountPath: /etc/oci/
              readOnly: true
            - name: kubernetes
              mountPath: /etc/kubernetes
              readOnly: true
            - mountPath: /var/run/shared-tmpfs
              name: shared-tmpfs
      volumes:
        - name: config
          secret:
            secretName: oci-volume-provisioner
        - name: kubernetes
          hostPath:
            path: /etc/kubernetes
        - name: shared-tmpfs
          emptyDir: {}
      dnsPolicy: ClusterFirst
      hostNetwork: true
      imagePullSecrets:
        - name: image-pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: csi-oci-{{ if .Values.customHandle }}{{ .Values.customHandle }}-{{ end }}node-sa
      serviceAccountName: csi-oci-{{ if .Values.customHandle }}{{ .Values.customHandle }}-{{ end }}node-sa
      terminationGracePeriodSeconds: 30
      tolerations:
        - operator: Exists
